<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicStore.Domain\MusicStore.Domain.csproj" />
    <ProjectReference Include="..\MusicStore.Repository\MusicStore.Repository.csproj" />
  </ItemGroup>

</Project>
