<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>e578a84a-8d53-49c5-8925-adf05b8c9370</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\**" />
    <Content Remove="wwwroot\images\**" />
    <EmbeddedResource Remove="wwwroot\images\**" />
    <None Remove="wwwroot\images\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\MusicStore.Repository.MySql.csproj" />
    <ProjectReference Include="..\MusicStore.Api\MusicStore.Api.csproj" />
    <ProjectReference Include="..\MusicStore.Domain\MusicStore.Domain.csproj" />
    <ProjectReference Include="..\MusicStore.Repository\MusicStore.Repository.csproj" />
  </ItemGroup>

</Project>
